services:
  frontend_dev:
    image: node:18-alpine
    container_name: ads_frontend_dev
    working_dir: /app
    environment:
      - API_URL=http://api:8000
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    ports:
      - "3001:3000"
    depends_on:
      - api
    networks:
      - ads_network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"
    restart: unless-stopped

networks:
  ads_network:
    external: false
